#!/usr/bin/env python
#Creando objetos para arreglar problemas
mruvtb = 0
#Creando bucle para las opciones
entrada = False
while entrada == False:
	a = raw_input("""!!!NOTA IMPORTANTE: NUMEROS CON DECIMALES ESCRIBILOS CON PUNTO NO CON COMA!!!
Elige una de las siguientes opciones:
1) M.R.U.
2) M.R.U.V.
3) M.C.U.
4) M.C.U.V.
5) Caida libre
Escribe el numero y presiona enter: """)
#Movimiento rectilineo uniforme
	if a == "1":
		mrut = False
		while mrut == False:
			mrutt = raw_input("!!!NOTA IMPORTANTE: NUMEROS CON DECIMALES ESCRIBILOS CON PUNTO NO CON COMA!!! \nQue quieres calcular? \n1)TIEMPO \n2)VELOCIDAD \n3)DISTANCIA \nEscribi la primera letra (en minuscula) de la palabra y pulsa enter:")
			if mrutt == "2":
				print float(input("Escribi la distancia en metros y apreta enter: ")) / input("Escribi el tiempo en segundos y presiona enter: "), "m/s, es tu velocidad."
				mrut = True
			elif mrutt == "1":
				print float(input("Escribi la distancia en metros y apreta enter: ")) / input("Escribi la velocidad en M/S (metros por segundo) y apreta enter: "), "s, es tu tiempo."
				mrut = True
			elif mrutt == "3":
				print float(input("Escribi la velocidad en M/S (metros por segundo) y apreta enter: ")) * input("Escribi el tiempo en segundos y presiona enter: "), "m, es tu distancia"
				mrut = True
			else:
				print "Esa opcion no es valida, presiona enter para continuar", raw_input()
		entrada = True
#Movimiento rectilineo uniformemente variado
	elif a == "2":
		mruvt = False
		while mruvt == False:
			mruvtt = raw_input("!!!NOTA IMPORTANTE: NUMEROS CON DECIMALES ESCRIBILOS CON PUNTO NO CON COMA!!! \nQue quieres calcular? \n1)ACELERACION \n2)TIEMPO \n3)VELOCIDAD \n4)DISTANCIA \nEscribi el numero y pulsa enter: ")
			if mruvtt == "1":
				mruvtb = input("Escribi la velocidad[Si NO tenes velocidad escribi 1 y apreta enter] en m/s (metros por segundo) y apreta enter: ")
			if mruvtb == 1:
				v = float(input("Escribi la distancia en metros y apreta enter: ")) / input("Escribi el tiempo en segundos y presiona enter: ")**2
				print v, "m/s^2, es tu aceleracion"
				mruvt = True
				exit()
			if mruvtb != 0:
				print float(mruvtb) / input("Escribi el tiempo en segundos y presiona enter: "), "m/s^2, es tu aceleracion"
				mruvt = True
				exit()
			if mruvtt == "2":
				print float(input("Escribi la velocidad en M/S (metros por segundo) y apreta enter: ")) / input("Escribi la aceleracion en m/s^2 (metros por segundo al cuadrado) y apreta enter: "), "s, es tu tiempo."
				mruvt = True
				exit()
			if mruvtt == "3":
				print input("Escribi la aceleracion en m/s^2 (metros por segundo al cuadrado) y apreta enter: ") * float(input("Escribi el tiempo en segundos y presiona enter: ")), "m/s, es tu velocidad."
				mruvt = True
				exit()
			if mruvtt == "4":
				print input("Escribi la aceleracion en m/s^2 (metros por segundo al cuadrado) y apreta enter: ") * float(input("Escribi el tiempo en segundos y presiona enter: "))**2, "m, es tu distancia."
				mruvt = True
				exit()
			else:
				print "Esa opcion no es valida, presiona enter para continuar", raw_input()
		entrada = True
#Movimiento circular
	elif a == "3":
		mcu = False
		while mcu == False:
			mcut = raw_input("!!!NOTA IMPORTANTE: NUMEROS CON DECIMALES ESCRIBILOS CON PUNTO NO CON COMA!!! \nQue quieres calcular? \n1)VELOCIDAD ANGULAR \n2)VELOCIDAD TANGENCIAL \n3)R.P.M. \nEscribi el numero y pulsa enter: ")
			if mcut == "1":
				print 6.28 / input("Escribi el tiempo en segundos y apreta enter: "), "1/s, es tu velocidad angular."
				mcu = True
			elif mcut == "2":
				print (6.28 / input("Escribi el tiempo en segundos y apreta enter: ") * input("Escribe tu radio en metros y apreta enter: ")), "m/s, es tu velocidad tangencial."
				mcu = True
			elif mcut == "3":
				print (input("Escribi tu velocidad en rad/s y apreta enter: ") / 6.28) * 60, "R.P.M."
				mcu = True
			else:
				print "Esa opcion no es valida, presiona enter para continuar", raw_input()
		entrada = True
#Movimiento circular variado
	elif a == "4":
		mcuv = False
		while not mcuv:
			mcuvt = raw_input("!!!NOTA IMPORTANTE: NUMEROS CON DECIMALES ESCRIBILOS CON PUNTO NO CON COMA!!! \nQue quieres calcular? \n1)ACELERACION CENTRIPETA \n2)FUERZA CENTRIPETA")
			if mcuvt == "1":
				print (float(input("Escribi la velocidad angular en rad/s y apreta enter: ")) ** 2) * input("Escribi tu radio en metros y apreta enter: "), "m/s^2, es tu aceleracion."
				mcuv = True
			if mcuvt == "2":
				print float(input("Escribi tu masa en kg y pulsa enter: ")) * input("Escribi tu aceleracion en m/s^2 y pulsa enter: "), "N, es tu fuerza."
				mcuv = True
		entrada = True
#Caida libre
	elif a == "5":
		cait = False
		while cait == False:
			caitl = raw_input("!!!NOTA IMPORTANTE: NUMEROS CON DECIMALES ESCRIBILOS CON PUNTO NO CON COMA!!! \nQue quieres calcular? \n1)TIEMPO \n2)DISTANCIA \n3)VELOCIDAD FINAL \nEscribi el numero y pulsa enter: ")
			if caitl == "1":
				print ((float(input("Escribi la altura en metros y apreta enter: ")) * 2) / 9.8) ** 0.5, "s, es tu tiempo."
				cait = True
			if caitl == "2":
				print (float(input("Escribi el tiempo en segundos y apreta enter: ")) ** 2) * 4.9, "m, es tu distancia."				
				cait = True
			if caitl == "3":
				catil = float(input("Escribi el tiempo en segundos y apreta enter: ")) * 9.8, "m/s, es tu velocidad."
				cait = True
			else:
				print "Esa opcion no es valida, presiona enter para continuar", raw_input()
		entrada = True
#Fin del bucle	
	else:
		print "Esa opcion no es valida, presiona enter para continuar", raw_input()
